#!/bin/bash

echo "🧪 Stripe Webhook Testing Guide"
echo "================================"
echo ""
echo "✅ Backend is running on: http://localhost:3002"
echo "✅ Webhook endpoint: http://localhost:3002/payment/stripe/webhook"
echo ""
echo "📋 Testing Steps:"
echo ""
echo "STEP 1: Open a new terminal and start Stripe listener"
echo "-------------------------------------------------------"
echo "Run this command in a NEW terminal window:"
echo ""
echo "  stripe listen --forward-to http://localhost:3002/payment/stripe/webhook"
echo ""
echo "This will:"
echo "  - Connect to Stripe"
echo "  - Show you a webhook signing secret (whsec_...)"
echo "  - Forward all Stripe events to your local server"
echo ""
echo "STEP 2: Update your .env with the NEW webhook secret"
echo "-----------------------------------------------------"
echo "The 'stripe listen' command will display a webhook secret like:"
echo "  whsec_1234567890abcdefghijklmnop"
echo ""
echo "Update backend/.env with this NEW secret:"
echo "  STRIPE_WEBHOOK_SECRET=whsec_[the-new-secret-from-stripe-listen]"
echo ""
echo "Then restart your backend server!"
echo ""
echo "STEP 3: Trigger a test webhook"
echo "-------------------------------"
echo "In another terminal, run:"
echo ""
echo "  stripe trigger checkout.session.completed"
echo ""
echo "Or trigger other events:"
echo "  stripe trigger payment_intent.succeeded"
echo "  stripe trigger charge.succeeded"
echo ""
echo "STEP 4: Check your backend logs"
echo "--------------------------------"
echo "You should see logs like:"
echo "  ✅ Webhook verified: checkout.session.completed"
echo "  🎯 Processing checkout.session.completed..."
echo "  ✅ Webhook checkout.session.completed processed successfully"
echo ""
echo "🔍 Debugging Tips:"
echo "==================="
echo ""
echo "If you see 'signature verification failed':"
echo "  1. Make sure you updated STRIPE_WEBHOOK_SECRET"
echo "  2. Make sure you restarted the backend after updating .env"
echo "  3. The secret from 'stripe listen' must match .env"
echo ""
echo "If you see 'timestamp outside tolerance zone':"
echo "  1. Check your system clock: date"
echo "  2. Make sure clock is synchronized"
echo ""
echo "If you see 'raw body is not a Buffer':"
echo "  1. Check middleware order in main.ts"
echo "  2. express.raw() must come BEFORE express.json()"
echo ""
echo "📊 Check webhook health:"
echo "  curl http://localhost:3002/payment/stripe/webhook/health"
echo ""
echo "🎯 Ready to test? Follow the steps above!"
