#!/bin/bash

echo "=========================================="
echo "🧪 REDIS CACHE TESTING SCRIPT"
echo "=========================================="
echo ""
echo "This script will:"
echo "1. Make first API call (should be CACHE MISS - hits database)"
echo "2. Wait 2 seconds"
echo "3. Make second API call (should be CACHE HIT - from Redis)"
echo ""
echo "Watch the backend terminal for color-coded logs:"
echo "  🟢 GREEN  = CACHE HIT (data from Redis)"
echo "  🟡 YELLOW = CACHE MISS (data not in Redis)"
echo "  🔵 CYAN   = CACHE SET (storing data in Redis)"
echo "  🟣 MAGENTA = DATABASE QUERY (fetching from MongoDB)"
echo "  🔴 RED    = CACHE DELETE (removing from Redis)"
echo ""
echo "=========================================="
echo ""

echo "📍 Test 1: Fetching public courses (First time - should miss cache)"
echo "Making request to: http://localhost:3002/courses/public"
echo ""
curl -s http://localhost:3002/courses/public | jq -r '.message' 2>/dev/null || echo "Response received"
echo ""
echo "✅ First request completed"
echo ""

echo "⏳ Waiting 2 seconds..."
sleep 2
echo ""

echo "📍 Test 2: Fetching public courses again (Should hit cache)"
echo "Making request to: http://localhost:3002/courses/public"
echo ""
curl -s http://localhost:3002/courses/public | jq -r '.message' 2>/dev/null || echo "Response received"
echo ""
echo "✅ Second request completed"
echo ""

echo "=========================================="
echo "🎯 TESTING COMPLETE"
echo "=========================================="
echo ""
echo "Check your backend terminal to see:"
echo "  - First request: CACHE MISS → DATABASE QUERY → CACHE SET"
echo "  - Second request: CACHE HIT (much faster!)"
echo ""
echo "The cache is working if you see:"
echo "  1. Yellow 'CACHE MISS' on first request"
echo "  2. Magenta 'DATABASE QUERY' with timing"
echo "  3. Cyan 'CACHE SET' storing the data"
echo "  4. Green 'CACHE HIT' on second request"
echo ""
