#!/bin/bash

echo "🔍 Webhook Secret Verification Guide"
echo "====================================="
echo ""
echo "Current webhook secret in .env:"
grep "STRIPE_WEBHOOK_SECRET" .env
echo ""
echo "⚠️  IMPORTANT: This secret MUST match your Stripe Dashboard webhook secret!"
echo ""
echo "📋 Steps to get the correct webhook secret:"
echo ""
echo "1. Go to: https://dashboard.stripe.com/test/webhooks"
echo ""
echo "2. Find your webhook endpoint for ngrok:"
echo "   URL: https://estimate-character-draw.ngrok-free.dev/payment/stripe/webhook"
echo ""
echo "3. Click on the webhook endpoint"
echo ""
echo "4. Click 'Signing secret' → 'Reveal'"
echo ""
echo "5. Copy the secret (starts with 'whsec_')"
echo ""
echo "6. Update backend/.env:"
echo "   STRIPE_WEBHOOK_SECRET=whsec_[the-secret-from-dashboard]"
echo ""
echo "7. Restart your backend server"
echo ""
echo "🎯 Common Issues:"
echo ""
echo "❌ Using the wrong secret:"
echo "   - Each webhook endpoint has its OWN secret"
echo "   - Local testing (stripe CLI) uses a DIFFERENT secret"
echo "   - Dashboard webhooks use a DIFFERENT secret"
echo ""
echo "✅ Solution:"
echo "   - Use the secret from the SPECIFIC webhook endpoint"
echo "   - For ngrok: use the secret from the ngrok webhook in Dashboard"
echo "   - For local stripe CLI: use the secret shown when running 'stripe listen'"
echo ""
echo "📊 Test after updating:"
echo "   Trigger a test payment and check backend logs for:"
echo "   ✅ Webhook verified: checkout.session.completed"
